ZEROWrapper/ZEROWrapper/ZEROWrapper/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('construction/', include('construction.urls')),
]

ZEROWrapper/ZEROWrapper/accounts/urls.py
from django.urls import path
from .views import HomeView, UserRegistView, UserLoginView, UserLogoutView, UserView


app_name = 'accounts'
urlpatterns = [
    path('home/', HomeView.as_view(), name='home'),
    path('regist/', UserRegistView.as_view(), name='regist'),
    path('user_login/', UserLoginView.as_view(), name='user_login'),
    path('user_logout/', UserLogoutView.as_view(), name='user_logout'),
    path('user/', UserView.as_view(), name='user'),
]

ZEROWrapper/ZEROWrapper/construction/urls.py
from django.urls import path
from .views import ConstructionListView


app_name = 'construction'
urlpatterns = [
    path('construction_list/', ConstructionListView.as_view(), name='construction_list'),
]

ZEROWrapper/ZEROWrapper/templates/base.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ZERO Wrapper</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <!-- Bootstrap CSS for datepicker -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
          <!-- アプリ名 -->
          <a class="navbar-brand" href="#"><strong>ZERO Wrapper</strong></a>
          <!-- ハンバーガーメニュー -->
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <!-- 各種メニューボタン -->
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="accounts:home">ホーム</a>
              </li>
              {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:user_logout' %}">ログアウト</a>
              </li>
              {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:user_login' %}">ログイン</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:regist' %}">ユーザ登録</a>
              </li>
              {% endif %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'construction:construction_list' %}">工事リスト</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:user' %}">ユーザ画面</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" target="_blank" href="{% url 'admin:index' %}">管理画面</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
      {% block content %}
      {% endblock %}
      <!-- ここからJavaScriptのインストール -->
      <!-- Bootstrap -->
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

       <!-- jQuery, popper.js, Bootstrap JS for datepicker -->
      <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
       <!-- bootstrap-datepicker -->
      <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css">
      <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js"></script>
      <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/locales/bootstrap-datepicker.ja.min.js"></script>

      <!-- bootstrap-datepickerの設定。工事リストの日付範囲指定で使用。 -->
      <script>
        $('.input-daterange').datepicker({
          language:'ja', // 日本語化
          format: 'yyyy-mm-dd', // DateTimeFieldのために日付表示をyyyy/mm/ddにフォーマット
        })
        .on({
          changeDate: function() {
            // datepickerの日付を取得
            console.log('開始日付 :', $('input[name="from"]').val() );  // 開始日付を取得
            console.log('終了日付 :', $('input[name="to"]').val() );    // 終了日付を取得
          }
        });
      </script>

</body>
</html>

ZEROWrapper/ZEROWrapper/templates/home.html
{% extends 'base.html' %}
{% block content %}
<h1>ホーム画面です。</h1>
{% endblock %}

ZEROWrapper/ZEROWrapper/templates/regist.html
{% extends 'base.html' %}
{% block content %}
<form method="POST">
    {% csrf_token %}
    <div class="container-fluid">
    <br>
    {{ form.as_p }}
    <button type="submit" class="btn btn-secondary">ユーザ登録</button>
    </div>
</form>
{% endblock %}

ZEROWrapper/ZEROWrapper/templates/regist_try.html
{% extends 'base.html' %}
{% block content %}
<form method="POST">
    {% csrf_token %}
    <div class="container-fluid">
        <br>
        {{ form.non_field_errors }}
        {% for item in form %}
        <div class="form-group col-md-4 col-md-offset-4 mx-5">
            <label for="{{item.id_for_label}}">{{item.label}}</label>
            <input
                type="{{item.field.widget.input_type}}"
                class="form-control"
                {% if item.field.required %}required{% endif %}
                name="{{item.name}}"
                id="{{item.id_for_label}}"
                placeholder="{{ item.help_text }}">
            {{ field.errors }}
        </div>
        {% endfor %}
        <br>
        <button type="submit" class="btn btn-secondary mx-5">ユーザ登録</button>
    </div>
</form>
{% endblock %}

ZEROWrapper/ZEROWrapper/templates/regist_try2.html
{% extends 'base.html' %}
{% block content %}
<form method="POST">
    {% csrf_token %}
    {{ form.non_field_errors }}
    {% for field in form %}
        <div class="field">
            {{ field.label_tag }}
            {{ field }}
            {% if field.help_text %}
                <span class="helptext">{{ field.help_text }}</span>
            {% endif %}
            {{ field.errors }}
        </div>
    {% endfor %}

    <div class="field">
        <button type="submit">送信</button>
    </div>
</form>
{% endblock %}

ZEROWrapper/ZEROWrapper/templates/user.html
{% extends 'base.html' %}
{% block content %}
<h1>ユーザ画面です。ログインが必要です。</h1>
{% endblock %}

ZEROWrapper/ZEROWrapper/templates/user_login.html
{% extends 'base.html' %}
{% block content %}
<form method="POST">
    {% csrf_token %}
    <br>
    <div class="col-md-6 col-md-offset-3 mx-5">
        <div class="form-group">
            <label for="exampleInputEmail1">メールアドレス</label>
            <input type="email" class="form-control" name="username" aria-describedby="emailHelp" placeholder="first_last@mail.toyota.co.jp">
        </div>
        <div class="form-group">
            <label for="exampleInputPassword1">パスワード</label>
            <input type="password" class="form-control" name="password" placeholder="半角英数字・記号を使用してください">
        </div>
        <div class="form-group form-check">
            <input type="checkbox" class="form-check-input" name="keep_login_session">
            <label class="form-check-label" for="exampleCheck1">ログイン状態を保持する</label>
        </div>
        <br>
        <button type="submit" class="btn btn-secondary">ログイン</button>
    </div>
</form>
{% endblock %}